
---
- hosts: ec2-52-77-250-56.ap-southeast-1.compute.amazonaws.com
  remote_user: ec2-user
  sudo: yes
  vars_files:
      - vars/user.yml

  tasks:

      
      - name: create user(s)
        user: name=${item} shell=/bin/bash  
        with_items: ${users}


      - stat: path=/home/${item}/.ssh/
        register: p
      - name: create .ssh folder for users
        file: path=/home/${item}/.ssh state=directory owner=${item} 
        with_items: ${users}
        when: p.stat.exists == False
        
      - stat: path=/home/${item}/.ssh/authorized_keys
        register: a
      - name: creating authorized_keys files
        file: path=/home/${item}/.ssh/authorized_keys state=touch owner=${item} 
        with_items: ${users}
        when: a.stat.exists == False


      - name: Copy Remote-To-Remote
        copy: src=/tmp/ec2-54-179-156-233.ap-southeast-1.compute.amazonaws.com/home/${item}/.ssh/id_rsa.pub dest=/home/${item}/.ssh/authorized_keys
        with_items: ${users}
 
